# Generated by Django 4.2.1 on 2023-05-04 16:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fucking_scraper", "0002_rename_items_item_rename_urls_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="slug",
            field=models.SlugField(blank=True, default="", editable=False),
        ),
    ]
