# Generated by Django 4.2.1 on 2023-05-06 20:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("fucking_scraper", "0005_lowestprice"),
    ]

    operations = [
        migrations.AddField(
            model_name="lowestprice",
            name="date",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
