# Generated by Django 4.2.1 on 2023-05-17 15:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fucking_scraper", "0006_lowestprice_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="EUR",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("eur_rate", models.FloatField()),
                ("date", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="PLN",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pln_rate", models.FloatField()),
                ("date", models.DateTimeField()),
            ],
        ),
    ]
