size_equivalents = {
    "XX-SMALL": "XXS",
    "EXTRA-SMALL": "XS",
    "X-SMALL": "XS",
    "XSMALL": "XS",
    "XS": "XS",
    "SMALL": "S",
    "S": "S",
    "MEDIUM": "M",
    "M": "M",
    "L": "L",
    "LARGE": "L",
    "X-LARGE": "XL",
    "XLARGE": "XL",
    "XL": "XL",
    "EXTRA-LARGE": "XL",
    "XX-LARGE": "XXL",
    "XXL": "XXL",
    "XXLARGE": "XXL",
    "2XL": "XXL",
    "3XL": "XXXL",
    "XXXL": "XXXL",
    "XXX-LARGE": "XXXL",
}

user_agent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.77 Safari/537.36"
